### ISSUE TITLE
New phenomenon 'FZ'

### ISSUE THREAD

**Issue by umpire274** [mivek/python-metar-taf-parser#1]
Hi I want to ask you to add a new phenomenon into 'metar_taf_parser/model/enum.py' into class 'Phenomenon':

FREEZING = 'FZ'

**Comment by umpire274** [comment]
I've made the update into my clone of your repository (new branch) but I can't push to you because I haven't write permission on your repository

**Comment by umpire274** [comment]
At this URL you can see a real Metar with phenomenon FZ

https://aviationweather.gov/metar/data?ids=KESF&format=decoded&hours=24&taf=off&layout=on

KESF 171753Z AUTO 04008KT 1 1/2SM FZRA BR BKN007 OVC020 M01/M02 A3002 RMK AO2 UPB05E08FZRAE05B08 CIG 004V012 SLP165 P0025 60045 I1008 I6017 T10061017 11006 21028 58020

**Comment by umpire274** [comment]
In case 

KESF 171746Z AUTO VRB05G15KT 3SM -FZRA BR OVC007 M01/M02 A3000 RMK AO2 UPB05E08FZRAE05B08 CIG 004V010 P0019 I1006 T10061017

there's a minus sign before FZRA means 'light freezing rain'

**Comment by mivek** [comment]
Hello @umpire274 

I assume you are talking of the token `FZRA`. The `FZ` part is the descriptive and the 'RA' is the phenomenon. As you can see [here](https://github.com/mivek/python-metar-taf-parser/blob/main/metar_taf_parser/model/enum.py#L41) FZ is in the enum Descriptive.

**Comment by umpire274** [comment]
hi @mivek 

thanks for your response. Sorry but I haven't read well your sources.
Now with metar_parse.weather_conditions[i].descriptive I've the 'FREEZING' string correctly.

This issue is closed.
