### ISSUE TITLE
'pip install' don't work correctly 

### ISSUE THREAD

**Issue by umpire274** [mivek/python-metar-taf-parser#10]
Hi Mivek.

When I try to install from scratch you plugin via 'pip install' obtain the installation about only 'metar_taf_parser_mivek-1.1.0.dist-info' but not the package.

Obtain this result whether when I launch 'pip install metar-taf-parser-mivek' from terminal or when import the package using 'PyCharm' UI functionallity.

<img width="1532" alt="Schermata 2021-04-20 alle 11 39 47" src="https://user-images.githubusercontent.com/340183/115374430-21100e00-a1cd-11eb-9c22-fbb009868722.png">

Can you help me?

Alex.

**Comment by mivek** [comment]
Hello @umpire274 

There is indeed a problem with the pypi package. I will reupload a new version ASAP.

**Comment by mivek** [comment]
I just deployed a new version `1.1.1`.
could you check if you can import it in your project?

**Comment by umpire274** [comment]
Yes Mivek, but your package goes into root directory of package and not in its subdir.

<img width="547" alt="Schermata 2021-04-21 alle 08 42 46" src="https://user-images.githubusercontent.com/340183/115508539-b7037180-a27d-11eb-917e-80fecea1a7c8.png">

**Comment by mivek** [comment]
@umpire274 please update to version 1.1.2 I fixed deployment to pypi

**Comment by umpire274** [comment]
Hi @mivek .

Now it's all ok. Thanks.

Alex.
