### ISSUE TITLE
can this taf parser be used to parse a dataframe with multiple (1000s) of rows?

### ISSUE THREAD

**Issue by JB-data** [mivek/python-metar-taf-parser#19]
Hi, 
is your parser capable of taking more than 1 row at the same time?
For instance if you load 1000s of TAFs in pandas, can you apply this function to parse it?
Or any example of how to use this in pyspark?

Thanks!

**Comment by mivek** [comment]
Hello @JB-data 

The parser can only parse a single code at the same time. If you want to parse 100 TAF messages you have to call the method `parse` 100 times
