### ISSUE TITLE
Add support for remarks PrecipitationBegCommand, PrecipitationEndCommand

### ISSUE THREAD

**Issue by aeharding** [mivek/python-metar-taf-parser#21]
Hello! I ❤️ this project. However, I see that the remark commands `PrecipitationBegCommand` and `PrecipitationEndCommand` are not in the python implementation.

See the Java implementation:

- https://github.com/mivek/MetarParser/blob/master/metarParser-parsers/src/main/java/io/github/mivek/command/remark/PrecipitationBegCommand.java
- https://github.com/mivek/MetarParser/blob/master/metarParser-parsers/src/main/java/io/github/mivek/command/remark/PrecipitationEndCommand.java

I'd love support added! I would be happy to make a PR but I'm not a python developer so it may take a bit to get something out there. Let me know.

**Comment by mivek** [comment]
Hello @aeharding 

Indeed, `PrecipitationBegCommand` and `PrecipitationEndCommand` are missing in this project. I'll add them soon.

**Comment by mivek** [comment]
Hello @aeharding 

The fix is in version 1.4.0 if the project. It also contains the fix regarding the remarks with `FCST`

**Comment by aeharding** [comment]
Awesome, thanks!
