### ISSUE TITLE
TAF Trends missing visibility

### ISSUE THREAD

**Issue by stephaniemayfieldrwdi** [mivek/python-metar-taf-parser#23]
I have tried several TAFs and they all seem to be missing visibility.

TAF AMD KEWR 191303Z 1913/2018 09006KT 5SM -RA BR BKN007 OVC025 
  FM191600 17007KT P6SM BKN020 
  FM192100 26008KT P3SM SCT030 SCT050 
  FM200000 29005KT P4SM SCT050 
  FM200600 VRB03KT P9SM SCT050

All the "FROM" trends are showing None for the visibility.   Other trend data appears to be intact.  Only the initial visibility is parsing.

![2022-05-24_17-02-00](https://user-images.githubusercontent.com/48362890/170092054-3b2267d0-bb06-476f-b2b3-65712c84eef0.jpg)

Thanks
Steph

**Comment by mivek** [comment]
Hello @stephaniemayfieldrwdi  

I managed to reproduce the bug. It is due to the `P` in the visibility part. When the visibility is written in miles it can have a `P` for `greater than` or a `M` for `less than`.
I will update the regex to include this.

**Comment by mivek** [comment]
Hello @stephaniemayfieldrwdi 

The fix has been merged. It is available in version 1.4.1.
