### ISSUE TITLE
COR, NIL and CNL flag support

### ISSUE THREAD

**Issue by aeharding** [mivek/python-metar-taf-parser#25]
Hello!

I am opening this issue in reference to an issue opened in my typescript port - aeharding/metar-taf-parser#16 regarding support for COR, NIL and CNL.

Examples:

COR (corrected): `TAF COR EDDS 201148Z 2012/2112 31010KT CAVOK TEMPO…B BECMG 2018/2021 33004KT BECMG 2106/2109 07005KT`

NIL (none): `SVMC 211703Z AUTO NIL`

CNL (cancelled): `TAF VTBD 281000Z 2812/2912 CNL=`

`CNL` and `NIL` support example in a different library here (parsed as a trend): https://github.com/hsdn/metar-taf/blob/master/src/Metar.php#L278

**Comment by aeharding** [comment]
There's some information here: https://www.dwd.de/EN/specialusers/aviation/download/products/metar_taf/metar_taf_download.pdf?__blob=publicationFile&v=3 but I don't see anything in the US handbook either.

Do you want me to separate out these issues, one for COR, and one for NIL/CNL?

**Comment by mivek** [comment]
No there is need to create separate issues. Thank you for the document. 
I will work on the feature

**Comment by mivek** [comment]
@aeharding 

I opened a PR to add flags support. Can you check it?

**Comment by aeharding** [comment]
Thanks so much for this! I’ll check it out in a few days. Away from the computer this weekend.

**Comment by aeharding** [comment]
Sorry for the delay. I just looked at this PR and it looks great! I just made a similar PR to the TS port https://github.com/aeharding/metar-taf-parser/pull/20
