### ISSUE TITLE
Error while importing metar-taf-parser library in python

### ISSUE THREAD

**Issue by ManojAgrawal** [mivek/python-metar-taf-parser#32]
Hello,

I get an error when I try to import metar-taf-parser library in my notebook as below. Strangely this error started showing up only recently. I am using a Macbook.

thanks,
Manoj Agrawal

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 15>()
     13 import unicodedata
     14 #from python_metar_taf_parser.metar_taf_parser.parser.parser import MetarParser, TAFParser
---> 15 from metar_taf_parser.parser.parser import MetarParser, TAFParser
     16 from bs4 import BeautifulSoup

File ~/opt/anaconda3/lib/python3.9/site-packages/metar_taf_parser/parser/parser.py:5, in <module>
      2 import re
      3 from datetime import time
----> 5 from metar_taf_parser.command.common import CommandSupplier
      6 from metar_taf_parser.command.metar import CommandSupplier as MetarCommandSupplier
      7 from metar_taf_parser.command.remark import RemarkCommandSupplier

File ~/opt/anaconda3/lib/python3.9/site-packages/metar_taf_parser/command/common.py:6, in <module>
      4 from metar_taf_parser.commons import converter
      5 from metar_taf_parser.commons.converter import convert_visibility
----> 6 from metar_taf_parser.model.enum import CloudQuantity, CloudType
      7 from metar_taf_parser.model.model import Visibility, Wind, WindShear, Cloud, AbstractWeatherContainer
     10 def set_wind_elements(wind: Wind, direction: str, speed: str, gust: str, unit: str):

File ~/opt/anaconda3/lib/python3.9/site-packages/metar_taf_parser/model/enum.py:3, in <module>
      1 import enum
----> 3 from metar_taf_parser.commons.i18n import _
      6 class CloudQuantity(enum.Enum):
      7     SKC = 'SKC'   # Sky clear

File ~/opt/anaconda3/lib/python3.9/site-packages/metar_taf_parser/commons/i18n.py:10, in <module>
      8 localedir = os.path.join(os.path.abspath(os.path.dirname(__file__)), '../locale')
      9 langAvailable = os.listdir(localedir)
---> 10 lang = locale.getdefaultlocale()[0][:2]
     11 if lang not in langAvailable:
     12     lang = 'en'

TypeError: 'NoneType' object is not subscriptable

**Comment by mivek** [comment]
Hello @ManojAgrawal 

Did you install the metar_taf_parser using pip?

What command do you run to get this error?

I tried on Debian but I could not reproduce your error.

According to the stacktrace the variable `localedir` is None.

**Comment by ManojAgrawal** [comment]
Hi Kevin,

Yes, I had installed the library using pip. Actually it worked fine earlier but then all of a sudden I started getting this error just when I try to import the library into the notebook. Might have to do something with an update on my MacBook. Not sure.

Thanks,
Manoj Agrawal

**Comment by ManojAgrawal** [comment]
HI Kevin,

I just tried again and was able to import the library without errors. Not sure how but the problem seems to have been resolved somehow. 
thanks,
Manoj Agrawal

**Comment by ManojAgrawal** [comment]
Resolved! thanks

**Comment by ManojAgrawal** [comment]
Aargh...the error started coming again
![Screen Shot 2022-11-28 at 9 49 05 AM](https://user-images.githubusercontent.com/20389089/204346247-e8a144c0-5bfd-407b-a127-a9568de417ec.png)

**Comment by mivek** [comment]
@ManojAgrawal 

I cannot reproduce the problem so I think you will have to debug it.
In a python terminal run the following

```
import locale

print(locale.getdefaultlocale())
```
 and try to understand why the variable is empty.

**Comment by ManojAgrawal** [comment]
Sure, will try to figure out. thanks
