### ISSUE TITLE
Weather conditions with 1 descriptive + 2 phenomenons or just 3 phenomenons are not recognized

### ISSUE THREAD

**Issue by ManojAgrawal** [mivek/python-metar-taf-parser#33]
Hello,

Weather conditions with one descriptive and two phenomenons are not recognized. For example for 
1. "CYVM 282100Z 36028G36KT 1SM -SN DRSN VCBLSN OVC008 M03/M04 A2935 RMK SN2ST8 LAST STFFD OBS/NXT 291200UTC SLP940"

there is no weather condition for 'VCBLSN'

2. 'KDEN 240638Z 01018G30KT 3SM FZDZSN BR BKN014CB OVC019 03/01 A2979 RMK AO2 PK WND 36030/0631 LTG DSNT N AND NE RAB16SNB34 TSB09E28E37B38 FRQ LTGICCCCG OHD-N TS OHD-N MOV N'

there is no weather condition entry for 'FZDZSN'

Also Weather conditions with 3 phenomenons are not recognized. For example for 
3. "KEWR 020551Z 03008KT 5SM SNPLRA BR BKN008 OVC012 01/M01 A3013 RMK AO2 RAB29PLB48 SLP201 931000 P0003 60003 T00061011 10017 20006 56028

Strangely, 1 descriptor + 3 Phenomenons or 4 phenomenons work fine.

thanks,
Manoj agrawal

**Comment by mivek** [comment]
Hello @ManojAgrawal 

This is a known issue. Here is the link to the issue in the java version https://github.com/mivek/MetarParser/issues/432.

I am working on a fix.

**Comment by ManojAgrawal** [comment]
Thanks Kevin. Also, do you have a suggestion on the import error (issue #32) that I am getting on my Mac?

File ~/opt/anaconda3/lib/python3.9/site-packages/metar_taf_parser/commons/i18n.py:10, in
8 localedir = os.path.join(os.path.abspath(os.path.dirname(file)), '../locale')
9 langAvailable = os.listdir(localedir)
---> 10 lang = locale.getdefaultlocale()[0][:2]
11 if lang not in langAvailable:
12 lang = 'en'

**Comment by mivek** [comment]
Hello @ManojAgrawal 

The bug is fixed in version 1.6.0 of the project. It is available on pypi
