### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by deepskyai** [mivek/python-metar-taf-parser#37]
Hi, with the validity and especially the FM objects. Do we extract as a string? Or as a date time? And are they linked in any to the weather that comes after the FM time?

**Comment by mivek** [comment]
Hello @deepskyai 

The `FM` objects use the [FMValidity ](https://github.com/mivek/python-metar-taf-parser/blob/main/metar_taf_parser/model/model.py#L790)object as validity. This object inherits from the [AbstractValidity](https://github.com/mivek/python-metar-taf-parser/blob/main/metar_taf_parser/model/model.py#L511).
The properties available on the FMValidity are
- start_day
- start_hour
- start_minutes

All these properties are integer
