### ISSUE TITLE
Error on getting METAR info's

### ISSUE THREAD

**Issue by umpire274** [mivek/python-metar-taf-parser#38]
I've installed the new version 1.6.1 and when I run my personal code obtain an error.

This is the my Python code:

`# Create the window
window = sg.Window('METAR and TAF Reader', layout)

while True:
    event, values = window.read()
    # See if user wants to quit or window was closed
    if event == sg.WINDOW_CLOSED or event == 'Quit':
        break

    try:
        metar = Metar(values['-INPUT-'].upper())

        properties = metar.text_recover()

        metar_parse = MetarParser().parse(properties[1])
...
`

and this is the error I get:

> Traceback (most recent call last):
> File "/Users/umpire274/Il mio Drive/Development/workspace/PycharmProject/metar_reader/metar_reader.py", line 126, in <module>
>    metar_parse = MetarParser().parse(properties[1])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/umpire274/Library/Python/3.11/lib/python/site-packages/metar_taf_parser/parser/parser.py", line 230, in parse 
> command.execute(metar, metar_tab[index])
>  File "/Users/umpire274/Library/Python/3.11/lib/python/site-packages/metar_taf_parser/command/metar.py", line 65, in execute
>    runway.thickness = DepositThickness(matches[0][3])
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 695, in __call__
>    return cls.__new__(cls, value)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 1111, in __new__ 
>    raise ve_exc
> ValueError: '02' is not a valid DepositThickness

If you need any further infos write me.

Alex.

**Comment by umpire274** [comment]
I've tried to downgrade to 1.6.0 and your library is running again correctly

**Comment by mivek** [comment]
Hello @umpire274 

Do you have the error on every Metar you are trying to parse? 
Can you provide a metar that triggers the error?

**Comment by umpire274** [comment]
UUDD and ULMM goes in error, while LIRF and EHAM are OK.

Alex.

**Comment by mivek** [comment]
Ok but do you have the whole code of the METAR ?

**Comment by umpire274** [comment]
UUDD 212100Z 20005MPS 8000 -FZRA SCT005 M01/M02 Q1010 R14R/590335 NOSIG

ULMM 212100Z 14001MPS 9999 BKN020 M07/M07 Q0994 R13/490236 NOSIG RMK QFE739


From the website https://sto.iki.fi/metar/
————

METAR Runway Report

METAR reports may include runway reports which contain information about snow/water coverage and friction coefficient. A runway report consists of eight digits in five groups (RRRRERCReReRBRBR) with the following interpretation:

RRRR	ER	CR	eReR	BRBR
Runway designator. The numerical identifier of the runway in question. 88 means all runways, 99indicates repetition of previous report.

If there are two parallel runways, the right one is indicated by adding 50 to its number. For example, runway 04L (or 04) is denoted by 04, whereas 54 means runway 04R.

Type of deposit on runway.

0: Clear and dry
1: Damp
2: Wet or puddles
3: Frost
4: Dry snow
5: Wet snow
6: Slush
7: Ice
8: Compacted snow
9: Frozen ridges
/: Not reported
Extent of deposit.

1: 1–10 %
2: 11–25 %
5: 26–50 %
9: 51–100 %
Depth of deposit.

00: Less than 1 mm
01…90: The depth in millimeters
92: 10 cm
93: 15 cm
94: 20 cm
95: 25 cm
96: 30 cm
97: 35 cm
98: 40 cm
99: Runway not in use
Friction coefficient or braking action

01…90: Friction coefficient times 100. For example, 37 indicates a friction coefficient of 0.37.
91: Poor braking action
92: Poor/medium braking action
93: Medium braking action
94: Medium/good braking action
95: Good braking action
99: Unreliable measurement
//: Not given
Note: CLRD may replace elements t, e and dd if the runway has been cleared of deposits. For example, 54CLRD95 means runway 04R cleared, braking action good.


————

Alex.

**Comment by mivek** [comment]
Hello @umpire274 

I created a PR to fixx the bug. Do you want to have a look at it ?

**Comment by umpire274** [comment]
Do you have release the new version, maybe 1.6.2?

**Comment by mivek** [comment]
No, I only created the pull request for now so you can have a look at the changes.
