### ISSUE TITLE
Probability for TEMPO Group

### ISSUE THREAD

**Issue by ManojAgrawal** [mivek/python-metar-taf-parser#41]
Hello,

I am trying the TAF parser as below:

x = TAFParser().parse('TAF LFPG 150500Z 1506/1612 17005KT 6000 SCT012 PROB60\nTEMPO 1509/1511 3000 BR BKN006 PROB40')

When I read the probabilities, they are correct
x.trends[0].probability = 60
x.trends[1].probability = 40

however when I check the trend type, I get this for the first trend

x.trends[0].type.value = TEMPO

![image](https://user-images.githubusercontent.com/20389089/216192293-971129d4-3ff4-462e-be14-45910aecb51b.png)

Is this the expected behavior?

thanks,

Manoj Agrawal

**Comment by mivek** [comment]
Hello @ManojAgrawal 

Yes this is the expected behaviour. The parser does not rely on line breaks, PROB tokens are often prefix of TEMPO.
I invite you to read this issue https://github.com/mivek/MetarParser/issues/157 and the according PR https://github.com/mivek/MetarParser/pull/165

**Comment by ManojAgrawal** [comment]
Hi @mivek 

Thanks for the reply. So, from what I understand, probabilities could be a prefix or can come later, so it can be 'PROB40 TEMPO....' or 'TEMPO....PROB40'. That complicate things, don't they :-)

thanks again

**Comment by mivek** [comment]
Yeah, it is sometimes complicated to understand whether the probability is with the previous TEMPO or the following.
I will close the issue, if you have another question do not hesitate to reopen it or open a new one
