### ISSUE TITLE
TAF parser cannot parse multiple 

### ISSUE THREAD

**Issue by whc4017** [mivek/python-metar-taf-parser#44]
The library is only able to return the last max/min temperature of TAF.

For example, when using TAFParse on 'TAF VHHH 011700Z 0118/0224 09010KT 7000 FEW020 SCT035 TX21/0207Z TN16/0123Z TN17/0223Z \n TEMPO 0203/0209 33010KT \n TEMPO 0209/0213 VRB05KT', it returns {'_temperature': 17, '_day': 2, '_hour': 23}, corresponding to TN17/0223Z.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/61936815/233247876-3aec0a2e-90b8-453e-98b9-9109d8e44f8e.png">

**Comment by mivek** [comment]
Hello @whc4017 

This is the first time I see the minimal temperature reported multiple times in a TAF.
Do you have any documentation on the topic ?
