### ISSUE TITLE
Some METAR and TAF report can not be parsed

### ISSUE THREAD

**Issue by expormz** [mivek/python-metar-taf-parser#45]
I use this great library for parse weather report, most of reports are parsed greatly,but some report can not be parsed,like:

METAR ZSNB 050000Z 18005MPS 9999 SCT030CB 26/22 Q1001 BECMG TL002024005G11MPS TSRA=

TAF ZSYT 042112Z 0500/0524 36004MPS 3200 BR FEW002 BKN010 BKN023TX15/0506Z TN11/0521Z TEMPO 0500/0506 1500 -SHRA BKN002 BKN010 BECMG0503/0504 FEW010 BKN023=

please fix it and thank you.

**Comment by mivek** [comment]
Hello @expormz 

Can you please provide more information ?
Do you get any error ?
What is the expected result ? What result do you get ?
