### ISSUE TITLE
Human readable summary?

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [mivek/python-metar-taf-parser#47]
Hi!

First of all, thank you for creating this comprehensive package! It looks very clean and even includes i18n.

However, I'm looking for a convenient way to convert raw METAR and TAF to human readable format just like https://www.metar-taf-decoder.com/ do. I want to integrate it into my telegram bot.

I'm currently using `METAR` and `pytaf` packages, but I have to install both and write some customized code to display additional things like airport name etc. into their summary. I wonder if there is a easy way or some example code to achieve the same thing here. What the other two packages does is basically [this](https://github.com/python-metar/python-metar/blob/main/metar/Metar.py#L1099). It is a very common functionality, so I expect this package should have a similar method to get a summary. Not sure if anyone have the same need, but it seems to be very common. Could you please provide some sample code to construct a summary based on parsed objects?

If such functionality is not available at the moment but PR welcome, I may find some time to draft a PR. No guarantee when I will have some time. Might be months from now.

Thank you!

**Comment by mivek** [comment]
Hello @jqqqqqqqqqq 

Thank you for your interest in the project.
The website [https://www.metar-taf-decoder.com/](https://www.metar-taf-decoder.com/) uses the [java ](https://github.com/mivek/MetarParser) version of the project and the frontend is a angular application.
I do not directly use the string representation of METAR and TAF objects but the objects attributes and a template from the angular application.

Implementing a `toString` method was in my TODO list for this project. I may have a local branch for it but I never finished the work.

I can implement  a`__str__` method to match the `toString` version of the java project

**Comment by devleaks** [comment]
Yes, the current code and readme only presents the "parsing" of METAR and TAF, but we need a little doc on object hierarchy and organisation and how to get the information out of the parsed structure. Otherwise, the parallel between METAR and TAF is very well abstracted in the hierarchy.
Thank you.

**Comment by mivek** [comment]
@jqqqqqqqqqq I opened a PR to fix the issue.
