### ISSUE TITLE
Printing model objects produces output with undesirable line breaks or formatting

### ISSUE THREAD

**Issue by cherls** [mivek/python-metar-taf-parser#58]
Reproduction:
```
from metar_taf_parser.parser.parser import MetarParser
metar = MetarParser().parse("CYTZ 010000Z AUTO 33013G21KT 9SM -RA BKN017 OVC046 06/05 A2977 RMK SLP084")
print(metar)
```
Printing the Metar object results in a poorly formatted `__repr__` output from https://github.com/mivek/python-metar-taf-parser/pull/49. As you can see, there are some odd line breaks and indentations, which affects readability. 

<img width="1062" alt="image" src="https://github.com/mivek/python-metar-taf-parser/assets/9567369/457138ec-dc87-4e53-9433-a7533007bd7a">

I recommend we remove the line breaks and update the code to use f-strings to fix the issue.

**Comment by mivek** [comment]
Hello @cherls

Thanks for the suggestion, I will use the f-strings
